[workspace]
resolver = "2"
members = [
]

[workspace.package]
license = "AGPL-3.0-only"
edition = "2021"
repository = "https://github.com/Polyfrost/Nexus"
documentation = "https://docs.polyfrost.org/nexus"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://polyfrost.org"
authors = ["Polyfrost"]

[workspace.dependencies]