/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
	queries:
		{ key: '', input: never, result: never } |
		{ key: 'test.me', input: never, result: number },
	mutations:
		{ key: '', input: never, result: null } |
		{ key: 'test.me', input: never, result: null },
	subscriptions:
		{ key: '', input: never, result: string[] } |
		{ key: 'test.me', input: never, result: null }
}
