name: 🐞 Bug Report
description: Report a bug
labels:
    - kind/bug
    - status/needs-triage

body:
    - type: checkboxes
      id: product
      attributes:
          label: Product name
          description: What Polyfrost product are you using?
          options:
              - label: Website
              - label: Launcher
              - label: Installer

    - type: markdown
      attributes:
          value: |
              ## First of all
              1. Please search for [existing issues](https://github.com/polyfrost/nexus/issues?q=is%3Aissue) about this problem first.
              2. Make sure it's an issue with our products and not something else you are using.
              3. Remember to follow our community guidelines and be friendly.

    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: A clear description of what the bug is. Include screenshots if applicable.
          placeholder: Bug description
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Go to ...
              2. Click on ...
              3. See error

    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: A clear description of what you expected to happen.

    - type: textarea
      id: logs
      attributes:
          label: Stack trace (optional)
          render: Shell

    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Add any other context about the problem here.
